name: unprg_guide_maps
description: " A guide map application for Universidad Nacional Pedro Ruiz Gallo."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  concentric_transition: ^1.0.3
  marquee: ^2.3.0
  latlong2: ^0.9.1
  google_maps_flutter: ^2.12.1
  flutter_staggered_animations: ^1.1.1
  speech_to_text: ^7.0.0
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  location: ^8.0.0
  http: ^1.3.0
  convert: ^3.1.2
  google_maps_polyline: ^1.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/facultades/
    - assets/images/info_card_facultades/ficsa/img_ficsa.jpg
    - assets/images/unprg_logo.png
    - assets/images/fondo1.jpeg

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300